#!/bin/sh
# SPDX-FileCopyrightText: 2026 The RISE Project
# SPDX-License-Identifier: MIT

# Reject a commit message that attributes work to Claude/Anthropic - this repo's
# hard rule is that nothing (commit, PR title/body, comment) ever mentions an AI
# tool as an author. The recurring leak vector is the assistant/session boilerplate
# some tools auto-append to a commit message (`Co-Authored-By: Claude ...`,
# `Claude-Session: ...`, `Generated by Claude Code`), which slips past a reviewer
# who only checked the PR body/comment footers and not the commit message itself
# (PR #2151, and two commits on main during the same session, both went out this
# way despite an explicit no-attribution instruction).
#
# Usage:
#   check_no_ai_attribution.sh <file-with-commit-message>   # commit-msg hook use
#   git log --format=%B -1 <sha> | check_no_ai_attribution.sh -   # pre-push hook use
#
# Deliberately checks the commit message only, not file/diff content: a patch
# can legitimately carry a real upstream contributor's byline (a person can be
# named Claude), and this check has no way to tell that apart from an AI
# attribution trailer. The message text is ours to write, so it has no such
# ambiguity.

set -eu

pattern='claude|anthropic'

file="${1:?usage: check_no_ai_attribution.sh <file|->}"
if [ "$file" = "-" ]; then
    content="$(cat)"
else
    content="$(cat "$file")"
fi

hit="$(printf '%s\n' "$content" | grep -inE "$pattern" || true)"
if [ -n "$hit" ]; then
    echo "check_no_ai_attribution: commit message mentions Claude/Anthropic - this project never attributes work to an AI tool." >&2
    echo "  Offending line(s):" >&2
    echo "$hit" | sed 's/^/    /' >&2
    echo "  Remove any Co-Authored-By/Claude-Session/\"Generated by\" trailer and rewrite the message, then retry." >&2
    exit 1
fi

exit 0
