# SPDX-FileCopyrightText: 2025 BayLibre, SAS
# SPDX-License-Identifier: Apache-2.0

import glob
import html
import os
import re
from urllib.parse import quote

import packaging.version as packaging_version
import yaml

GITHUB_PYTHON_WHEELS_URL = "https://github.com/riseproject-dev/python-wheels/tree/main"
PYPI_INDEX_URL = "https://pypi.riseproject.dev/simple/"

# Match RST inline external refs: `Label <url>`_ or `Label <url>`__
RST_LINK_RE = re.compile(r"`([^`<]+?)\s*<([^>]+)>`_+")
PACKAGE_NORMALIZE_RE = re.compile(r"[-_.]+")


def normalize_package_name(package_name):
    """Return the normalized project name required by the Simple API."""
    return PACKAGE_NORMALIZE_RE.sub("-", package_name).lower()


def rst_to_md(text):
    """Convert the subset of RST inline syntax used in YAML comments to Markdown."""
    if not text:
        return text
    return RST_LINK_RE.sub(r"[\1](\2)", text)


def _callout(lines, label, text):
    """Append a just-the-docs callout block to ``lines``."""
    lines.append("")
    lines.append(f"{{: .{label} }}")
    for ln in rst_to_md(text).splitlines():
        lines.append(f"> {ln}" if ln else ">")
    lines.append("")


def generate_simple_page(yaml_file, output_html):
    """Generate a static PEP 503 package page from a package YAML file."""
    try:
        with open(yaml_file, "r", encoding="utf-8") as f:
            package_data = yaml.safe_load(f)
    except (FileNotFoundError, yaml.YAMLError) as e:
        print(f"Error reading {yaml_file}: {e}")
        return None, None

    package_name = package_data.get("package-name")
    if not package_name:
        print(f"Error reading {yaml_file}: package-name is missing")
        return None, None

    lines = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "  <head>",
        '    <meta charset="utf-8">',
        f"    <title>Links for {html.escape(package_name)}</title>",
        "  </head>",
        "  <body>",
        f"    <h1>Links for {html.escape(package_name)}</h1>",
    ]
    for version in package_data.get("versions", []):
        releases = version.get("releases")
        if releases is None:
            raise ValueError(
                f"{yaml_file}: version {version.get('version')} has no releases"
            )
        for release in releases:
            tag = release["tag"]
            for file_data in release.get("files", []):
                filename = file_data["filename"]
                href = (
                    "https://github.com/riseproject-dev/python-wheels/releases/"
                    f"download/{quote(tag, safe='')}/{quote(filename, safe='')}"
                    f"#sha256={file_data['sha256']}"
                )
                rendered_attrs = [f'href="{html.escape(href, quote=True)}"']
                requires_python = file_data.get("requires-python")
                if requires_python:
                    rendered_attrs.append(
                        'data-requires-python="'
                        f'{html.escape(str(requires_python), quote=True)}"'
                    )
                if "yanked" in file_data:
                    rendered_attrs.append(
                        f'data-yanked="{html.escape(str(file_data["yanked"] or ""), quote=True)}"'
                    )
                lines.append(
                    f"    <a {' '.join(rendered_attrs)}>{html.escape(filename)}</a>"
                )
    lines += ["  </body>", "</html>"]

    try:
        os.makedirs(os.path.dirname(output_html), exist_ok=True)
        with open(output_html, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
    except IOError as e:
        print(f"Error writing {output_html}: {e}")
        return None, None

    return package_name, output_html


def generate_md_page(yaml_file, output_md):
    """Generate a Markdown page from a single package YAML file."""
    try:
        with open(yaml_file, "r", encoding="utf-8") as f:
            package_data = yaml.safe_load(f)
    except FileNotFoundError as e:
        print(f"Error reading {yaml_file}: {e}")
        return None, None

    package_name = package_data.get("package-name", "Unknown Package")
    license_type = package_data.get("license")
    source_code = package_data.get("source-code")
    comment = package_data.get("comment")
    warning = package_data.get("warning")
    versions = package_data.get("versions", [])

    versions.sort(
        key=lambda v: packaging_version.parse(str(v["version"])), reverse=True
    )
    latest_version = str(versions[0]["version"]) if versions else None

    lines = [
        "---",
        f"title: {package_name}",
        "layout: default",
        "parent: Supported Packages",
        "---",
        "",
        "<!-- Auto-generated by generate_packages_doc.py. Do not edit manually. -->",
        "",
        f"# {package_name}",
        "",
    ]

    if "deprecated" in package_data:
        pypi_url = f"https://pypi.org/project/{package_name}/"
        lines += [
            "{: .warning }",
            "> This package is deprecated. PyPI now publishes newer versions of",
            "> this package for riscv64, and we will no longer maintain this",
            f"> package. Please use the version from [PyPI]({pypi_url}) instead.",
            ">",
            "> If you need a specific version between the latest available here",
            "> and the first available on PyPI, please open an",
            "> [Issue](https://github.com/riseproject-dev/python-wheels/issues)",
            "> and select `Package build request`.",
            "",
        ]

    if source_code:
        lines.append(f"**Source code:** [{source_code}]({source_code})")
        lines.append("")

    # Version picker: a dropdown that reveals one version panel at a time.
    # Without JavaScript every panel stays visible, so content degrades
    # gracefully; version-selector.js hides all but the selected panel.
    lines.append('<div class="version-selector">')
    lines.append(
        '  <label for="version-select"><strong>Select version:</strong></label>'
    )
    lines.append('  <select id="version-select" class="version-select">')
    for version in versions:
        version_number = str(version["version"])
        is_latest = version_number == latest_version
        option_label = f"{version_number} (latest)" if is_latest else version_number
        selected = " selected" if is_latest else ""
        lines.append(
            f'    <option value="{version_number}"{selected}>{option_label}</option>'
        )
    lines.append("  </select>")
    lines.append("</div>")
    lines.append("")

    for version in versions:
        version_number = str(version["version"])
        is_latest = version_number == latest_version

        lines.append(
            f'<div class="version-panel" markdown="1" '
            f'data-version="{version_number}">'
        )
        lines.append("")

        install_command = (
            f"pip install {package_name} --index-url {PYPI_INDEX_URL}"
            if is_latest
            else f"pip install {package_name}=={version_number} "
            f"--index-url {PYPI_INDEX_URL}"
        )
        lines += ["```bash", install_command, "```", ""]

        lic = version.get("license", license_type)
        if lic:
            lines.append(f"**License:** {lic}")
            lines.append("")

        releases = version.get("releases", [])
        if releases:
            release_links = []
            for release in releases:
                tag = release["tag"]
                release_url = (
                    "https://github.com/riseproject-dev/python-wheels/releases/tag/"
                    f"{quote(tag, safe='')}"
                )
                release_links.append(f"[{tag}]({release_url})")
            lines.append(f"**Download files:** {', '.join(release_links)}")
            lines.append("")
            for release in releases:
                gpl_sources = release.get("gpl-sources")
                if not gpl_sources:
                    continue
                tag = release["tag"]
                filename = gpl_sources.get("filename", "gpl-sources.tar")
                source_url = (
                    "https://github.com/riseproject-dev/python-wheels/releases/"
                    f"download/{quote(tag, safe='')}/{quote(filename, safe='')}"
                )
                description = gpl_sources.get("description")
                suffix = f" ({description})" if description else ""
                _callout(
                    lines,
                    "note",
                    f"[Sources of bundled GPL libraries]({source_url}){suffix}",
                )

        if "patched" in version and source_code:
            patch_link = (
                f"{GITHUB_PYTHON_WHEELS_URL}/"
                f"patches/{package_name}/{version_number}"
            )
            lines.append(
                f"**Patch applied for this version:** " f"[{patch_link}]({patch_link})"
            )

        if version.get("comment"):
            _callout(lines, "note", version["comment"])

        if version.get("warning"):
            _callout(lines, "warning", version["warning"])

        lines += ["</div>", ""]

    if comment:
        _callout(lines, "note", comment)

    if warning:
        _callout(lines, "warning", warning)

    try:
        with open(output_md, "w", encoding="utf-8") as f:
            f.write("\n".join(lines).rstrip() + "\n")
    except IOError as e:
        print(f"Error writing {output_md}: {e}")
        return None, None

    return package_name, output_md


def process_all_yaml_files():
    out_dir = os.path.dirname(os.path.abspath(__file__))
    yaml_files = sorted(glob.glob(os.path.join(out_dir, "*.yaml")))
    if not yaml_files:
        print(f"No YAML files found in {out_dir}")
        return

    package_entries = []
    simple_entries = []
    simple_dir = os.path.join(os.path.dirname(out_dir), "simple")
    for yaml_file in yaml_files:
        print(f"Processing {yaml_file}...")
        base = os.path.basename(yaml_file).replace(".yaml", ".md")
        md_file = os.path.join(out_dir, base)
        name, fname = generate_md_page(yaml_file, md_file)
        if name and fname:
            package_entries.append((name, os.path.basename(fname)))

        package_name = os.path.basename(yaml_file).removesuffix(".yaml")
        simple_file = os.path.join(
            simple_dir, normalize_package_name(package_name), "index.html"
        )
        simple_name, simple_fname = generate_simple_page(yaml_file, simple_file)
        if simple_name and simple_fname:
            simple_entries.append(simple_name)

    package_entries.sort(key=lambda x: x[0].lower())
    generate_index(package_entries, out_dir)
    generate_simple_index(simple_entries, simple_dir)


def generate_simple_index(package_names, simple_dir):
    """Generate the static root page for the PEP 503 Simple API."""
    lines = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "  <head>",
        '    <meta charset="utf-8">',
        "    <title>Simple index</title>",
        "  </head>",
        "  <body>",
        "    <h1>Simple index</h1>",
    ]
    for package_name in sorted(package_names, key=str.lower):
        normalized_name = normalize_package_name(package_name)
        lines.append(
            f'    <a href="{html.escape(normalized_name, quote=True)}/">{html.escape(package_name)}</a>'
        )
    lines += ["  </body>", "</html>"]

    index_path = os.path.join(simple_dir, "index.html")
    try:
        os.makedirs(simple_dir, exist_ok=True)
        with open(index_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        print(f"Generated: {index_path}")
    except IOError as e:
        print(f"Error writing {index_path}: {e}")


def generate_index(package_entries, out_dir):
    if not package_entries:
        print("No packages to list in index.md")
        return

    lines = [
        "---",
        "title: Supported Packages",
        "layout: default",
        "nav_order: 5",
        "has_children: true",
        "has_toc: false",
        "---",
        "",
        "<!-- Auto-generated by generate_packages_doc.py. Do not edit manually. -->",
        "",
        "# List of Supported Packages",
        "",
    ]
    for name, fname in package_entries:
        page = fname.replace(".md", ".html")
        lines.append(f"- [{name}]({page})")

    index_path = os.path.join(out_dir, "index.md")
    try:
        with open(index_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        print(f"Generated: {index_path}")
    except IOError as e:
        print(f"Error writing {index_path}: {e}")


if __name__ == "__main__":
    process_all_yaml_files()
