# SPDX-FileCopyrightText: 2026 The RISE Project
# SPDX-License-Identifier: MIT

name: Build workflow setup

on:
  workflow_call:

jobs:
  setup:
    if: github.event_name != 'pull_request' || github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - run: true
